language: cpp
dist: xenial
compiler: gcc

addons:
 apt:
  packages:
   - libboost-all-dev

install:
 # Qt5
 # is this necessary?
 # - sudo apt-get install -qq qt5-qmake qt5-default
    
 # Codecov
 - sudo pip install codecov
 
 # cppcheck
 # - sudo apt-get install -qq cppcheck
 
 # OCLint
 # - chmod +x ci/install_oclint 
 # - ./ci/install_oclint
 
script:
 # - make
 
 # Build and run the tests
 - qmake ./boost_test.pro
 - make --silent debug
 - travis_wait 60 ./BOOST_TEST.app 
  
  # Build and run and profile normal program
   - qmake ./console/console.pro
  # - make --silent release
  # - time ./console
  # - gprof ./console > gprof.log
  # - head gprof.log -n 1000
  
  # Get code coverage
 - chmod +x ci/get_code_cov 
 - ./ci/get_code_cov
 - codecov
  
 # cppcheck
 # - cppcheck --quiet --error-exitcode=0 . 
  
 # Call OCLint
 # - chmod +x ci/do_oclint 
 # - ./ci/do_oclint
 
after_success:
 
 # Codecov
 - bash <(curl -s https://codecov.io/bash)
